"""Updating PostRecord to allow Null Images

Revision ID: 03561d006253
Revises: 78dd5bf1e6cf
Create Date: 2026-09-03 14:08:42.274161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03561d006253'
down_revision = '78dd5bf1e6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
